### PR TITLE
HKISD-156 Fix CSV download

### PR DESCRIPTION
**Pull request by andbeda**
**Fix: When downloading a CSV report, the page previously attempted to open a pop-up window.**

- Moved CSV data fetching logic into a custom hook (`useCsvData`)

- Extracted CSV generation and download functionality into utility functions

- Updated `DownloadCsvButton` component to prevent pop-up window during download

- Removed unnecessary `react-csv` and `@types/react-csv` library (hasn't been updated for over 2 years)

**Testing:**
Verify that the CSV-download functionality works correctly with no pop-up blockers interfering with the download process.

### CODE REVIEW

**Review by millaeerola — CHANGES_REQUESTED** [review]
Pop-up issue is fixed nicely! 👍 
There seems to be an issue with creating the csv data, since at least the headers look a bit incorrect now. First screenshot from this feature branch and second from develop branch:
Screenshot 2024-09-03 at 10 45 20
Screenshot 2024-09-03 at 10 47 49

**Comment by andbeda** [comment]
> Pop-up issue is fixed nicely! 👍 There seems to be an issue with creating the csv data, since at least the headers look a bit incorrect now. First screenshot from this feature branch and second from develop branch: Screenshot 2024-09-03 at 10 45 20 Screenshot 2024-09-03 at 10 47 49

problems with multi-line wrapping fixed in [a2fb1ab](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/259/commits/a2fb1abb67df161d0cee4a98ffcc1dadc2b43ccc)

**Review by millaeerola — CHANGES_REQUESTED** [review]
I found this issue from the "Rakentamisohjelma (yli 1 milj hankkeet)" where empty values are showing up as undefined. In develop branch they are shown as empty.
Screenshot 2024-09-05 at 12 58 02
Screenshot 2024-09-05 at 12 58 09
Otherwise seems to be working correctly now 👍

**Comment by andbeda** [comment]
resolved in [e6e8da8](https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/259/commits/e6e8da8b6ae0ece06f6b9409dcc89e7df15b88df)

**Review by millaeerola — APPROVED** [review]
Looks good! 👍

**Pull request merged**
